server:
  port: 8090
  forward-headers-strategy: native
  compression:
    enabled: false
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    add-properties: false
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.9.113.57:3306/newhalo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: user
    password: panzhe123user


    # H2 database configuration.
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/.halo/db/halo
#    username: admin
#    password: 123456
#
#  h2:
#    console:
#      settings:
#        web-allow-others: false
#      path: /h2-console
#      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
      location: ${java.io.tmpdir}
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: ['httptrace', 'metrics','env','logfile','health']
logging:
  level:
    run.halo.app: INFO
  file:
    path: ${user.home}/.halo/logs

halo:
  download-timeout: 5m